const express = require("express")
const app = express()
const connect = require("./config/db")
const cors = require("cors")
const albumRouter = require("./controllers/album.controller")
const artistRouter = require("./controllers/artist.controller")
const songRouter = require("./controllers/song.controller")
const {register,login} = require("./controllers/auth.controller")
app.use(cors())
app.use(express.json())
app.use("/album",albumRouter)
app.use("/artist",artistRouter)
app.use("/song",songRouter)
app.post("/login",login)
app.post("/signup",register)

app.listen(3001,(req,res)=>{
    connect()
    console.log("Server started on port 3001")
})